// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lllcafzzyosseqldfhcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsbGNhZnp6eW9zc2VxbGRmaGN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzY2OTgsImV4cCI6MjA2MDk1MjY5OH0.XlCdpxUsdW8cYLfPULS6EzzeJWnkKwL44goWoxMVXxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);