// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnqyqnkynyombyngzdcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InducXlxbmt5bnlvbWJ5bmd6ZGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MjU5MTMsImV4cCI6MjA2MjMwMTkxM30.707QSiDM7e5pV5Vpc7oHXNwEvar3m_ATW-J_TZ23rXE"; // You'll need to get this from your Supabase dashboard

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
